name: spatialdata-env
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - libexpat=2.7.0
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsqlite=3.49.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.1.1
  - python=3.12.10
  - readline=8.2
  - setuptools=80.8.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - pip:
    - napari==0.6.1
    - spatialdata==0.4.0

